# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Backprop Ninja
full_name: Anshul Yadav
email: ee1170565_at_iitd.ac.in
email2: anshulyadaviitd@gmail.com
description: "Journey of an Electrical Engineer."
baseurl: "" 
url: "http://anshul3899.github.io" # the base hostname & protocol for your site
github_username:  anshul3899
twitter_username: anshulyadav1911
linkedin_username: anshulyadaviitd
include: ['_pages']

# Build settings
markdown: kramdown
highlighter: rouge
